#----------------------------------------
# General
#----------------------------------------

# Prompts
autoload -Uz promptinit
promptinit

# Command completion
autoload -Uz compinit
compinit

# Remembering recent directories
autoload -Uz chpwd_recent_dirs cdr add-zsh-hook
add-zsh-hook chpwd chpwd_recent_dirs


#----------------------------------------
# Keybindings
#----------------------------------------


#----------------------------------------
# Path and environment variables
#----------------------------------------

# Path to GNU Coreutils
if [ -d "/usr/local/opt/coreutils/libexec/gnubin" ] ; then
    export PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"
fi

# Path to GNU Coreutils man pages
if [ -d "/usr/local/opt/coreutils/libexec/gnuman" ] ; then
    export MANPATH="/usr/local/opt/coreutils/libexec/gnuman:$MANPATH"
fi

# Customise LS_COLORS if necessary
# TODO: Set specific colours for different file types
#export LS_COLORS=$LS_COLORS:'di=0;94:'

#----------------------------------------
# Alias
#----------------------------------------

alias cd..="cd .."
alias ..="cd .."

alias ls="ls -F --color=always" 
alias ll="ls -lhF --color=always" 
alias la="ls -lahF --color=always" 

alias grep="grep --color=always"

alias egrep="egrep --color=always"

alias ssh_proxy="ssh -o \"ProxyCommand=nc -X connect -x 127.0.0.1:8079 %h %p\"" 


#----------------------------------------
# Functions
#----------------------------------------

# Set proxy
function set_proxy() {
    export http_proxy=http://127.0.0.1:8079
    export https_proxy=http://127.0.0.1:8079
}

# Unset proxy
function unset_proxy() {
    unset http_proxy
    unset https_proxy
}


#----------------------------------------
# nvm
#----------------------------------------

# Source: https://gist.github.com/fl0w/07ce79bd44788f647deab307c94d6922
# Ref: http://broken-by.me/lazy-load-nvm/
lazynvm() {
  unset -f nvm node npm
  export NVM_DIR=~/.nvm
  [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm
}
 
nvm() {
  lazynvm
  nvm $@
}
 
node() {
  lazynvm
  node $@
}
 
npm() {
  lazynvm
  npm $@
}

#----------------------------------------
# Themes
#----------------------------------------
source $HOME/.zsh/theme.zsh


#----------------------------------------
# Plugins
#----------------------------------------
fpath=(/usr/local/share/zsh-completions $fpath)
source /usr/local/share/zsh-autosuggestions/zsh-autosuggestions.zsh
#source /usr/local/share/zsh-history-substring-search/zsh-history-substring-search.zsh
source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
